### ISSUE TITLE
Display individual file progress in web uploader

### ISSUE THREAD

**Issue by poma** [poma/hotsapi#11]
And improve overall uploader design and usability. I hope someone with better frontend knowledge than me takes this task.

**Comment by ekzor** [comment]
i'll work on this if no one else is currently doing it

**Comment by ekzor** [comment]
I have a working version of the web uploader with individual file progress bars. I hope to eventually add file counts and a result summary as well, similar to what the app has.

I'll wait for my changes in pull request #25 to go through before committing more to the same file, since those changes are simple and have a functional impact on the uploader (allowing mass uploads from chrome), whereas this stuff is all cosmetic with far more code changes.

(Off-topic: I'm pretty new to git/github; can anyone tell me what the right etiquette is here? Should I wait for the previous pull request to go through, or should I just commit everything as it's completed and let it be reviewed/approved in phases on a per-commit basis?)

**Comment by poma** [comment]
Yeah just add to existing PR. I'll review and merge when I have enough spare time

**Comment by poma** [comment]
fixed by #25
