### ISSUE TITLE
Current Rate Limiting makes API difficult or impossible to use.

### ISSUE THREAD

**Issue by andrewfinnell** [poma/hotsapi#120]
The current rate limits are too cumbersome. While I understand why we want to rate limit this API, the current settings are impractical. I suggest we have two modes to the API. One that is anonymous with a Rate Limit, and one that requires identifying who we are and the use a Token to remove or at least significantly reduce the current rate limit.

I just tested the API in Postman and locked myself out with three requests. Rate Limits are typically in place to stop hundreds to thousands of requests within a second, not 3 within 5 seconds.

I can possibly assist with creating a simple Bearer Token or JWT system. Even if it's something where a user pays $1/month just to ensure they aren't bots.

**Comment by MGatner** [comment]
I believe the rates are there because of the incredibly cost-effective server spec. Up until just recently @poma was paying about $300/month out-of-pocket to keep this running. Dumping old replays has brought it to almost self-sustaining, so he is working on opening up some of these performance gains. I think the approach though is to offer a BigQuery dataset for scenarios where you need access to a lot more roelays than the API makes feasible.

**Comment by poma** [comment]
Rate limit on the list of replays currently is 30/minute. Other API endpoints are unlimited. If you do more requests than that, probably you are seeding DB with data which is now done with .csv dumps.
