### ISSUE TITLE
Storing talent picks?

### ISSUE THREAD

**Issue by tobz** [poma/hotsapi#13]
I'd love to work on this, but would you be open to storing the talent picks for each replay and returning that in the API?  Maybe as part of an extended response?

My assumption is that if you have hero picks (with their talents), map, game type, and who won/lost, then you've already provided 80 - 90% of the information that most people use HotsLogs for, and would make it VERY easy to build a dashboard that people would really be interested with.

I mean, overall, I think the model you've tried to lay out is enviable, but hardly anyone is going to be willing to set up the infrastructure to sync the replay files and parse them all over again.  Your API is most valuable to new developers when it already provides that 80 - 90% of what people want.

**Comment by poma** [comment]
I fully agree, talent picks should be available via API. They are extracted from a large file in replay (gameEvents) so they should be processed in a background task to not slow down uploader.

Before release I though that developers want access to replay file bu it turned out that most just want access to metadata via API. So I guess we will develop it in that direction.

**Comment by poma** [comment]
By the way we currently don't have enough CPU resources for second stage parsing so I'm putting this in backlog for now.
