### ISSUE TITLE
Add "Upload to HotsLogs" checkbox to a web uploader

### ISSUE THREAD

**Issue by poma** [poma/hotsapi#41]
Now that we support uploads to hotslogs, we can enable it in a web uploader. Checkbox needs to add `uploadToHotslogs=true` as a post or get parameter.

**Comment by ekzor** [comment]
the wording should be made clear that there's no extra burden to the user (i.e. they don't have to upload the same file twice). Maybe along the lines of "allow hotslogs to access your replays" or something else that's more brief.

Aside, I wonder why we'd push replays to hotslogs rather than asking them to pull from us.

**Comment by poma** [comment]
> the wording should make it clear that there's no extra burden to the user

I agree. Don't know hot to make it shorter though. Uploader's checkbox is "Send a copy to hotslogs" but 
it's not clear from the text that servers sends it instead of client.

> I wonder why we'd push replays to hotslogs rather than asking them to pull from us.

Because Barrett is not decided yet whether he wants to integrate, but we want to attract more users. Uploading everything in one place is more convenient.

**Comment by ekzor** [comment]
I think "Send a copy to hotslogs" is fine. We can add a tooltip that explains there's no extra burden to the user, so that anyone who cares has a way to find out.

>but we want to attract more users. Uploading everything in one place is more convenient.

Agreed.

In terms of functionality, the checkbox must be checked *before* the upload starts for this parameter to be included in the submission. There's two ways I can see us handling this for a reasonable user experience:

- Grey out the checkbox after uploading starts so that users aren't misled into thinking they can tick the box later and get the same functionality. This means we can keep the form mostly as-is and just add a checkbox with a parameter, like you said in your first post.

- Alternatively, we could set up a second server-side script to to copy to hotslogs after uploads are completed. Modify the existing server-side file upload script to return the id of each successful upload and, after the entire batch is done, pass them to the second script. Then the user can click the checkbox at any point and it will do what they expect it to.

Obviously the first option will be quicker to implement in the short term and I think that would be a reasonable first step. Does the uploader app only act on uploads that are in progress/not yet complete?

**Comment by poma** [comment]
Yes let's go with the first option. Uploader app works in the same way.
