### ISSUE TITLE
Support parallel uploads in web uploader

### ISSUE THREAD

**Issue by poma** [poma/hotsapi#46]
Replace `sequentialUploads: true,` with `limitConcurrentUploads: 3,`

JS for status updates needs some changes too because currently it updates the topmost status, which will be incorrect in case of parallel uploads.

**Comment by ekzor** [comment]
Yes, the current JS is designed for single uploads. rather than refer to all `.upload_table_progress` elements when manipulating progress bars, the code should refer to a specific element.

i can handle this.

regarding sequential uploads, are the throttling settings set to permit multiple uploads at once? I seemed to trip the laravel throttler a few times during testing and I'm not entirely sure how.

**Comment by poma** [comment]
it allows 300 requests per minute from a single ip

**Comment by poma** [comment]
I'm planning to make an update post on reddit tomorrow, would be cool if we manage to finish this and logo before that.

**Comment by ekzor** [comment]
Alright, I'll try to make some progress tonight.

**Comment by ekzor** [comment]
I won't have time to get multi-file uploads completed and thoroughly tested tonight, but should have time to put it together tomorrow. I tried to take care of all the other little easier things in my latest pull request.
