### ISSUE TITLE
Talent backfill

### ISSUE THREAD

**Issue by mjibson** [poma/hotsapi#65]
I'm really happy to see talents have started to make their way into the API. However considering there are over 3 million uploads and less than 40k games with talents filled in, may I suggest that instead of backfilling by upload ID, which has lots of really old games, that the backfill instead fills in by descending game date? This would allow my project and others to get talent data from games being played on the current patch quickly, and then optionally fill in the older stuff over time.

Thanks for your great work and effort around all of this.

**Comment by poma** [comment]
It was just a test run to check that most replays are parsed successfully. Once I'll have spare time I'll launch a mass scan, it should take around 1 day. The only bottleneck here is DB insert rate, so it may be faster or slower depending on that.

It turned out Amazon is shitty at scaling IOPS. I have to buy 1 TB (!) of DB storage to have a full 3k IOPS capacity and even then can't scale it back. I have to manually take an sql dump and then insert it into a new smaller DB instance. Currently service is running at 100 IOPS, that's even slower than magnetic discs.

**Comment by mjibson** [comment]
Gotcha. Thanks.
