### ISSUE TITLE
Why talents and score not showed?

### ISSUE THREAD

**Issue by Qws** [poma/hotsapi#94]
http://hotsapi.net/api/v1/replays?min_id=80&start_date=2018-01-02&end_date=2018-01-20&with_players=true

![image](https://user-images.githubusercontent.com/3944421/35195781-c07c3604-fec8-11e7-8748-9a4f18b078f4.png)

As you can see, few data are marked as "null". Is there a way to show the data?

**Comment by enicn** [comment]
https://hotsapi.net/api/v1/replays/6209125
Same thing happens to me too. What should I do to get these score data?

**Comment by wakuflair** [comment]
Same to me.
I used `Heroes.ReplayParser.dll` from HotsLogs to parse the same replay file, and the score and talents data can be parsed.

**Comment by wakuflair** [comment]
It may be related to #91 ?

**Comment by poma** [comment]
Extended replay parsing is currently slowed down due to insufficient funds. You can still download and parse them locally.

**Comment by lukaspj** [comment]
Hey @poma, what is the estimated goal on Patreon to support extended replay parsing? Is it just the 250$ p/m or is it more?

**Comment by lukaspj** [comment]
Furthermore, would it be possible to have a HotSAPI parser akin to the uploader?
One which would pick replays off a message queue, parse it on the client-side (like my own desktop computer) then put the parsed result onto the message queue again?

I don't know about your infrastructure, and how easy it is to make a Replay accessible for a client without having to register for Amazon in order to pay for data-transfer, but the client-side of it seems fairly simple.

I would find it silly to download the replays, just to parse them locally and then keep the results for myself, and it would give people and alternative way of contributing.

**Comment by Zemill** [comment]
I would like to know what the cost is as well.  I just went through and parsed ~600k replays through an amazon lambda for about $50.  How many replays are you getting a week/month?

**Comment by poma** [comment]
The server doesn't trust client enough to receive parsed data from them. Costs for a stable parser server are not very high and soon I want to enable it permanently, we are close to being self sustainable now
